#!/usr/bin/env php

<?php

require __DIR__.'/vendor/autoload.php';

use Sender\Command\SenderCommand;
use Symfony\Component\Dotenv\Dotenv;
use Symfony\Component\Console\Application;

$dotenv = new Dotenv();
$dotenv->load(__DIR__.'/.env');

$application = new Application();

$application->add(new SenderCommand());

$application->run();